<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ConjugadorIrregularesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $verbos = [
            /** IRREGULARES */
            [
                'verbos_categoria' => 2,
                'verbos_id' => 33,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'ofrezco',
                'verb' => 'biete',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 33,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'ofreces',
                'verb' => 'bietest',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 33,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'ofrece',
                'verb' => 'bietet',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 33,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'ofrecemos',
                'verb' => 'bieten',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 33,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'ofrecen',
                'verb' => 'bietet',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 33,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'ofrecen',
                'verb' => 'bieten',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 34,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'permanezco',
                'verb' => 'bleibe',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 34,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'permaneces',
                'verb' => 'bleibst',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 34,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'permanece',
                'verb' => 'bleibt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 34,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'permanecemos',
                'verb' => 'bleiben',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 34,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'permanecen',
                'verb' => 'bleibt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 34,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'permanecen',
                'verb' => 'bleiben',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 35,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'pienso',
                'verb' => 'denke',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 35,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'piensas',
                'verb' => 'denkst',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 35,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'piensa',
                'verb' => 'denkt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 35,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'pensamos',
                'verb' => 'denken',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 35,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'piensan',
                'verb' => 'denkt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 35,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'piensan',
                'verb' => 'denken',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 36,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'aconsejo',
                'verb' => 'empfehle',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 36,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'aconsejas',
                'verb' => 'empfiehlst',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 36,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'aconseja',
                'verb' => 'empfiehlt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 36,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'aconsejamos',
                'verb' => 'empfehlen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 36,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'aconsejan',
                'verb' => 'empfehlt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 36,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'aconsejan',
                'verb' => 'empfehlen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 37,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'como',
                'verb' => 'esse',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 37,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'comes',
                'verb' => 'ißt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 37,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'come',
                'verb' => 'ißt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 37,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'comemos',
                'verb' => 'essen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 37,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'comen',
                'verb' => 'eßt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 37,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'comen',
                'verb' => 'essen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 38,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'conduzco',
                'verb' => 'fahre',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 38,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'conduces',
                'verb' => 'fährst',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 38,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'conduce',
                'verb' => 'fährt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 38,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'conducimos',
                'verb' => 'fahren',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 38,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'conducen',
                'verb' => 'fahrt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 38,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'conducen',
                'verb' => 'fahren',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 39,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'caigo',
                'verb' => 'fall',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 39,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'caes',
                'verb' => 'fällst',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 39,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'cae',
                'verb' => 'fällt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 39,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'caemos',
                'verb' => 'fallen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 39,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'caen',
                'verb' => 'fallt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 39,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'caen',
                'verb' => 'fallen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 40,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'encuentro',
                'verb' => 'finde',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 40,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'encuentras',
                'verb' => 'findest',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 40,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'encuentra',
                'verb' => 'findet',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 40,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'encontramos',
                'verb' => 'finden',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 40,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'encuentran',
                'verb' => 'findet',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 40,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'encontramos',
                'verb' => 'finden',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 41,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'doy',
                'verb' => 'gebe',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 41,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'das',
                'verb' => 'gibst',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 41,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'da',
                'verb' => 'gibt',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 41,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'damos',
                'verb' => 'geben',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 41,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'dan',
                'verb' => 'gebt',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 41,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'dan',
                'verb' => 'geben',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 42,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'voy',
                'verb' => 'gehe',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 42,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'vas',
                'verb' => 'gehst',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 42,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'va',
                'verb' => 'geht',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 42,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'vamos',
                'verb' => 'gehen',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 42,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'van',
                'verb' => 'geht',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 42,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'van',
                'verb' => 'gehen',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 43,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'ayudo',
                'verb' => 'helfe',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 43,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'ayudas',
                'verb' => 'hilfst',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 43,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'ayuda',
                'verb' => 'hilft',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 43,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'ayudamos',
                'verb' => 'helfen',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 43,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'ayudan',
                'verb' => 'helft',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 43,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'ayudan',
                'verb' => 'helfen',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 44,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'conozco',
                'verb' => 'kenne',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 44,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'conoces',
                'verb' => 'kennst',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 44,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'conoce',
                'verb' => 'kennt',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 44,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'conocemos',
                'verb' => 'kennen',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 44,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'conocen',
                'verb' => 'kennt',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 44,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'conocemos',
                'verb' => 'kennen',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 45,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'vengo',
                'verb' => 'komme',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 45,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'vienes',
                'verb' => 'kommst',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 45,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'viene',
                'verb' => 'kommt',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 45,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'venimos',
                'verb' => 'kommen',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 45,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'vienen',
                'verb' => 'kommt',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 45,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'vienen',
                'verb' => 'kommen',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 46,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'cargo',
                'verb' => 'lade',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 46,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'cargas',
                'verb' => 'lädst',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 46,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'carga',
                'verb' => 'lädt',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 46,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'cargamos',
                'verb' => 'laden',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 46,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'cargan',
                'verb' => 'ladet',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 46,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'cargan',
                'verb' => 'laden',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 47,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'dejo',
                'verb' => 'lasse',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 47,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'dejas',
                'verb' => 'läßt',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 47,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'deja',
                'verb' => 'läßt',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 47,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'dejamos',
                'verb' => 'lassen',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 47,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'dejan',
                'verb' => 'laßt',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 47,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'dejan',
                'verb' => 'lassen',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 48,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'leo',
                'verb' => 'lese',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 48,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'lees',
                'verb' => 'liest',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 48,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'lee',
                'verb' => 'liest',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 48,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'leemos',
                'verb' => 'lesen',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 48,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'leen',
                'verb' => 'lest',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 48,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'leen',
                'verb' => 'lesen',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 49,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'yazgo',
                'verb' => 'liege',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 49,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'yaces',
                'verb' => 'liegst',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 49,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'yace',
                'verb' => 'liegt',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 49,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'yacemos',
                'verb' => 'liegen',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 49,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'yacen',
                'verb' => 'liegt',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 49,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'yacen',
                'verb' => 'liegen',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 50,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'tomo',
                'verb' => 'nehme',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 50,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'tomas',
                'verb' => 'nimmst',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 50,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'toma',
                'verb' => 'nimmt',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 50,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'tomamos',
                'verb' => 'nehmen',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 50,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'toman',
                'verb' => 'nehmt',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 50,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'toman',
                'verb' => 'nehmen',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 51,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'cierro',
                'verb' => 'schließe',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 51,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'cierras',
                'verb' => 'schließt',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 51,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'cierra',
                'verb' => 'schließt',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 51,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'cerramos',
                'verb' => 'schließen',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 51,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'cierran',
                'verb' => 'schließt',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 51,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'cierran',
                'verb' => 'schließen',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 52,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'escribo',
                'verb' => 'schreibe',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 52,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'escribes',
                'verb' => 'schreibst',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 52,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'escribe',
                'verb' => 'schreibt',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 52,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'escribimos',
                'verb' => 'schreiben',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 52,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'escriben',
                'verb' => 'schreibt',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 52,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'escriben',
                'verb' => 'schreiben',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 53,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'veo',
                'verb' => 'sehe',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 53,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'ves',
                'verb' => 'siehst',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 53,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 've',
                'verb' => 'sieht',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 53,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'vemos',
                'verb' => 'sehen',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 53,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'ven',
                'verb' => 'seht',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 53,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'ven',
                'verb' => 'sehen',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 54,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'envío',
                'verb' => 'sende',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 54,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'envías',
                'verb' => 'sendest',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 54,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'envía',
                'verb' => 'sendet',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 54,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'envíamos',
                'verb' => 'senden',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 54,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'envían',
                'verb' => 'sendet',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 54,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'envían',
                'verb' => 'senden',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 55,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'hablo',
                'verb' => 'spreche',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 55,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'hablas',
                'verb' => 'sprichst',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 55,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'habla',
                'verb' => 'spricht',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 55,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'hablamos',
                'verb' => 'sprechen',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 55,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'hablan',
                'verb' => 'sprecht',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 55,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'hablan',
                'verb' => 'sprechen',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 56,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'estoy de pie',
                'verb' => 'stehe',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 56,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'estas de pie',
                'verb' => 'stehst',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 56,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'estas de pie',
                'verb' => 'steht',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 56,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'estamos de pie',
                'verb' => 'stehen',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 56,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'estan de pie',
                'verb' => 'steht',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 56,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'estan de pie',
                'verb' => 'stehen',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 57,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'llevo',
                'verb' => 'trage',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 57,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'llevas',
                'verb' => 'trägst',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 57,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'lleva',
                'verb' => 'trägt',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 57,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'llevamos',
                'verb' => 'tragen',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 57,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'llevan',
                'verb' => 'tragt',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 57,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'llevan',
                'verb' => 'tragen',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 58,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'encuentro',
                'verb' => 'treffe',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 58,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'encuentras',
                'verb' => 'triffst',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 58,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'encuentra',
                'verb' => 'trifft',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 58,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'encontramos',
                'verb' => 'treffen',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 58,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'encuentran',
                'verb' => 'trefft',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 58,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'encuentran',
                'verb' => 'treffen',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 59,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'olvido',
                'verb' => 'vergesse',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 59,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'olvidas',
                'verb' => 'vergessest',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 59,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'olvida',
                'verb' => 'vergesst',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 59,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'olvidamos',
                'verb' => 'vergessen',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 59,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'olvidan',
                'verb' => 'vergesst',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 59,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'olvidan',
                'verb' => 'vergessen',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 60,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'sé',
                'verb' => 'weiß',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 60,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'sabes',
                'verb' => 'weißt',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 60,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'sabe',
                'verb' => 'weiß',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 60,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'sabemos',
                'verb' => 'wißen',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 60,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'saben',
                'verb' => 'wißt',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 60,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'saben',
                'verb' => 'wißen',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 61,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'empiezo',
                'verb' => 'beginne',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 61,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'empiezas',
                'verb' => 'beginnst',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 61,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'empieza',
                'verb' => 'beginnt',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 61,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'empezamos',
                'verb' => 'beginnen',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 61,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'empiezan',
                'verb' => 'beginnt',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 61,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'empiezan',
                'verb' => 'beginnen',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 62,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'induzco',
                'verb' => 'bewege',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 62,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'induces',
                'verb' => 'bewegst',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 62,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'induce',
                'verb' => 'bewegt',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 62,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'inducimos',
                'verb' => 'bewegen',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 62,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'inducen',
                'verb' => 'bewegt',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 62,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'inducen',
                'verb' => 'bewegen',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 63,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'pido',
                'verb' => 'bitte',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 63,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'pides',
                'verb' => 'bittest',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 63,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'pide',
                'verb' => 'bittet',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 63,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'pedimos',
                'verb' => 'bitten',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 63,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'piden',
                'verb' => 'bittet',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 63,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'piden',
                'verb' => 'bitten',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 64,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'traigo',
                'verb' => 'bringe',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 64,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'traes',
                'verb' => 'bringst',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 64,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'trae',
                'verb' => 'bringt',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 64,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'traemos',
                'verb' => 'bringen',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 64,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'traen',
                'verb' => 'bringt',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 64,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'traen',
                'verb' => 'bringen',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
        ];

        DB::table('conjugador')->insert($verbos);
    }
}



























