<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ConjugadorRegularesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $verbos = [
            /** REGULARES */
            [
                'verbos_categoria' => 1,
                'verbos_id' => 1,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'respondo',
                'verb' => 'antworte',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 1,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'respondes',
                'verb' => 'antwortest',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 1,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'responde',
                'verb' => 'antwortet',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 1,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'respondemos',
                'verb' => 'antworten',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 1,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'responden',
                'verb' => 'antwortet',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 1,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'son/están',
                'verb' => 'antworten',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 2,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'trabajo',
                'verb' => 'arbeite',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 2,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'trabajas',
                'verb' => 'arbeitest',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 2,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'trabaja',
                'verb' => 'arbeitet',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 2,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'trabajamos',
                'verb' => 'arbeiten',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 2,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'trabajan',
                'verb' => 'arbeitet',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 2,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'trabajan',
                'verb' => 'arbeiten',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 3,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'pregunto',
                'verb' => 'frage',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 3,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'preguntas',
                'verb' => 'fragst',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 3,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'pregunta',
                'verb' => 'fragt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 3,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'preguntamos',
                'verb' => 'fragen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 3,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'preguntan',
                'verb' => 'fragt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 3,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'preguntan',
                'verb' => 'fragen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 4,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'creo',
                'verb' => 'glaube',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 4,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'crees',
                'verb' => 'glaubst',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 4,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'cree',
                'verb' => 'glaubt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 4,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'creemos',
                'verb' => 'glauben',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 4,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'creen',
                'verb' => 'glaubt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 4,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'creen',
                'verb' => 'glauben',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 5,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'vivir',
                'verb' => 'lebe',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 5,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'vives',
                'verb' => 'lebst',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 5,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'vive',
                'verb' => 'lebt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 5,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'vivimos',
                'verb' => 'leben',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 5,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'viven',
                'verb' => 'lebt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 5,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'viven',
                'verb' => 'leben',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 6,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'aprendo',
                'verb' => 'lerne',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 6,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'aprendes',
                'verb' => 'lernst',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 6,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'aprende',
                'verb' => 'lernt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 6,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'aprendemos',
                'verb' => 'lernen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 6,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'aprenden',
                'verb' => 'lernt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 6,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'aprenden',
                'verb' => 'lernen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 7,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'hago',
                'verb' => 'mache',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 7,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'haces',
                'verb' => 'machst',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 7,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'hace',
                'verb' => 'macht',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 7,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'hacemos',
                'verb' => 'machen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 7,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'hacen',
                'verb' => 'macht',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 7,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'hacen',
                'verb' => 'machen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 8,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'hablo',
                'verb' => 'rede',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 8,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'hablas',
                'verb' => 'redest',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 8,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'habla',
                'verb' => 'redet',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 8,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'hablamos',
                'verb' => 'reden',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 8,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'hablan',
                'verb' => 'redet',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 8,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'hablamos',
                'verb' => 'reden',
                'nivel' => 1,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 9,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'digo',
                'verb' => 'sage',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 9,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'dices',
                'verb' => 'sagst',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 9,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'dice',
                'verb' => 'sagt',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 9,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'decimos',
                'verb' => 'sagen',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 9,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'dicen',
                'verb' => 'sagt',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 9,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'dicen',
                'verb' => 'sagen',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 10,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'juego',
                'verb' => 'spiele',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 10,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'juegas',
                'verb' => 'spielst',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 10,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'juega',
                'verb' => 'spielt',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 10,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'jugamos',
                'verb' => 'spielen',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 10,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'juegan',
                'verb' => 'spielt',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 10,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'juegan',
                'verb' => 'spielen',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 11,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'construyo',
                'verb' => 'baue',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 11,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'construyes',
                'verb' => 'baust',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 11,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'construye',
                'verb' => 'baut',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 11,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'construimos',
                'verb' => 'bauen',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 11,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'construyen',
                'verb' => 'baut',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 11,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'construyen',
                'verb' => 'bauen',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 12,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'quiero decir',
                'verb' => 'bedeute',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 12,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'quieres decir',
                'verb' => 'bedeutest',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 12,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'quiere decir',
                'verb' => 'bedeutet',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 12,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'queremos decir',
                'verb' => 'bedeuten',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 12,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'quieren decir',
                'verb' => 'bedeutet',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 12,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'quieren decir',
                'verb' => 'bedeuten',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 13,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'formo',
                'verb' => 'bilde',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 13,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'formas',
                'verb' => 'bildest',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 13,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'forma',
                'verb' => 'bildet',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 13,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'formamos',
                'verb' => 'bilden',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 13,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'forman',
                'verb' => 'bildet',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 13,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'forman',
                'verb' => 'bilden',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 14,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'desarrollo',
                'verb' => 'entwickle',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 14,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'desarrollas',
                'verb' => 'entwickelst',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 14,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'desarrolla',
                'verb' => 'entwickelt',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 14,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'desarrollamos',
                'verb' => 'entwickeln',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 14,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'desarrollan',
                'verb' => 'entwickelt',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 14,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'desarrollan',
                'verb' => 'entwickeln',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 15,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'recuerdo',
                'verb' => 'erinnere',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 15,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'recuerdas',
                'verb' => 'erinnerest',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 15,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'recuerda',
                'verb' => 'erinnert',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 15,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'recordamos',
                'verb' => 'erinnern',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 15,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'recuerdan',
                'verb' => 'erinnert',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 15,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'recuerdan',
                'verb' => 'erinnern',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 16,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'aclaro',
                'verb' => 'erkläre',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 16,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'aclaras',
                'verb' => 'erklärst',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 16,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'aclara',
                'verb' => 'erklärt',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 16,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'aclaramos',
                'verb' => 'erklären',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 16,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'aclaran',
                'verb' => 'erklärt',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 16,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'aclaran',
                'verb' => 'erklären',
                'nivel' => 2,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 17,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'alcanzo',
                'verb' => 'erreiche',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 17,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'alcanzas',
                'verb' => 'erreichst',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 17,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'alcanza',
                'verb' => 'erreicht',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 17,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'alcanzamos',
                'verb' => 'erreichen',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 17,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'alcanzan',
                'verb' => 'erreicht',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 17,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'alcanzan',
                'verb' => 'arreichen',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 18,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'narro',
                'verb' => 'erzähle',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 18,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'narras',
                'verb' => 'erzählst',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 18,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'narra',
                'verb' => 'erzählt',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 18,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'narramos',
                'verb' => 'erzählen',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 18,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'narran',
                'verb' => 'erreicht',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 18,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'narran',
                'verb' => 'erzählen',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 19,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'falto',
                'verb' => 'fehle',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 19,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'faltas',
                'verb' => 'fehlst',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 19,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'falta',
                'verb' => 'fehlt',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 19,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'faltamos',
                'verb' => 'fehlen',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 19,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'faltan',
                'verb' => 'fehlt',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 19,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'faltan',
                'verb' => 'fehlen',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 20,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'sigo',
                'verb' => 'folge',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 20,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'sigues',
                'verb' => 'folgst',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 20,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'sigue',
                'verb' => 'folgt',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 20,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'seguimos',
                'verb' => 'folgen',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 20,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'siguen',
                'verb' => 'folgt',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 20,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'siguen',
                'verb' => 'folgen',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 21,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'siento',
                'verb' => 'fühle',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 21,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'sientes',
                'verb' => 'fühlst',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 21,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'siente',
                'verb' => 'fühlt',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 21,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'sentimos',
                'verb' => 'fühlen',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 21,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'sienten',
                'verb' => 'fühlt',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 21,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'sienten',
                'verb' => 'fühlen',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 22,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'guío',
                'verb' => 'führe',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 22,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'guías',
                'verb' => 'führst',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 22,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'guía',
                'verb' => 'führt',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 22,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'guíamos',
                'verb' => 'führen',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 22,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'guían',
                'verb' => 'führt',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 22,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'guían',
                'verb' => 'führen',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 23,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'pertenezco',
                'verb' => 'gehöre',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 23,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'perteneces',
                'verb' => 'gehörst',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 23,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'pertenece',
                'verb' => 'gehört',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 23,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'pertenecemos',
                'verb' => 'gehören',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 23,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'pertenecen',
                'verb' => 'gehört',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 23,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'pertenecen',
                'verb' => 'gehören',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 24,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'actúo',
                'verb' => 'handel',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 24,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'actúas',
                'verb' => 'handelst',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 24,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'actúa',
                'verb' => 'handelt',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 24,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'actúamos',
                'verb' => 'handeln',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 24,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'actúan',
                'verb' => 'handelt',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 24,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'actúan',
                'verb' => 'handeln',
                'nivel' => 3,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 25,
                'pronombre' => 'me',
                'pronomen' => 'ich',
                'verbo' => 'interesa',
                'verb' => 'interessiere',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 25,
                'pronombre' => 'te',
                'pronomen' => 'du',
                'verbo' => 'interesa',
                'verb' => 'interessierst',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 25,
                'pronombre' => 'le',
                'pronomen' => 'er/sie/es',
                'verbo' => 'interesa',
                'verb' => 'interessiert',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 25,
                'pronombre' => 'nos',
                'pronomen' => 'wir',
                'verbo' => 'interesa',
                'verb' => 'interessieren',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 25,
                'pronombre' => 'les',
                'pronomen' => 'ihr',
                'verbo' => 'actúan',
                'verb' => 'handelt',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 25,
                'pronombre' => 'les',
                'pronomen' => 'sie',
                'verbo' => 'interesa',
                'verb' => 'interessieren',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 26,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'compro',
                'verb' => 'kaufe',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 26,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'compras',
                'verb' => 'kaufst',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 26,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'compra',
                'verb' => 'kauft',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 26,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'compramos',
                'verb' => 'kaufen',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 26,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'compran',
                'verb' => 'kauft',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 26,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'compran',
                'verb' => 'kaufen',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 27,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'cuido',
                'verb' => 'kümmere',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 27,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'cuidas',
                'verb' => 'kümmerst',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 27,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'cuida',
                'verb' => 'kümmert',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 27,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'cuidamos',
                'verb' => 'kümmern',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 27,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'cuidan',
                'verb' => 'kümmert',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 27,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'cuidan',
                'verb' => 'kümmern',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 28,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'pongo',
                'verb' => 'lege',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 28,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'pones',
                'verb' => 'legst',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 28,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'pone',
                'verb' => 'legt',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 28,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'ponemos',
                'verb' => 'legen',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 28,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'ponen',
                'verb' => 'legt',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 28,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'ponen',
                'verb' => 'legen',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 29,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'pienso',
                'verb' => 'meine',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 29,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'piensas',
                'verb' => 'meinst',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 29,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'piensa',
                'verb' => 'meint',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 29,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'pensamos',
                'verb' => 'meinen',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 29,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'piensan',
                'verb' => 'meint',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 29,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'piensan',
                'verb' => 'meinen',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 30,
                'pronombre' => 'esta',
                'pronomen' => 'es',
                'verbo' => 'lloviendo',
                'verb' => 'regnen',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 31,
                'pronombre' => 'me',
                'pronomen' => 'ich',
                'verbo' => 'gusta',
                'verb' => 'schmecke',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 31,
                'pronombre' => 'te',
                'pronomen' => 'du',
                'verbo' => 'gusta',
                'verb' => 'schmekst',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 31,
                'pronombre' => 'le',
                'pronomen' => 'er/sie/es',
                'verbo' => 'compra',
                'verb' => 'schmeckt',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 31,
                'pronombre' => 'nos',
                'pronomen' => 'wir',
                'verbo' => 'gusta',
                'verb' => 'schmecken',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 31,
                'pronombre' => 'les',
                'pronomen' => 'ihr',
                'verbo' => 'gusta',
                'verb' => 'schmeckt',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 31,
                'pronombre' => 'les',
                'pronomen' => 'sie',
                'verbo' => 'gusta',
                'verb' => 'schmecken',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 32,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'estudio',
                'verb' => 'studiere',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 32,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'estudias',
                'verb' => 'studierst',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 32,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'estudia',
                'verb' => 'studiert',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 32,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'estudiamos',
                'verb' => 'studieren',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 32,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'estudian',
                'verb' => 'studiert',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 32,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'estudian',
                'verb' => 'studieren',
                'nivel' => 4,
                'created_at' => Carbon::now(),
                'tiempo_id' => 2,
            ],
        ];

        DB::table('conjugador')->insert($verbos);
    }
}
