<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ConjugadorTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $verbos = [
            /** REGULARES */
            [
                'verbos_categoria' => 1,
                'verbos_id' => 1,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'respondo',
                'verb' => 'antworte',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 1,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'respondes',
                'verb' => 'antwortest',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 1,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'responde',
                'verb' => 'antwortet',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 1,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'respondemos',
                'verb' => 'antworten',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 1,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'responden',
                'verb' => 'antwortet',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 1,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'son/están',
                'verb' => 'antworten',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 2,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'trabajo',
                'verb' => 'arbeite',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 2,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'trabajas',
                'verb' => 'arbeitest',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 2,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'trabaja',
                'verb' => 'arbeitet',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 2,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'trabajamos',
                'verb' => 'arbeiten',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 2,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'trabajan',
                'verb' => 'arbeitet',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 2,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'trabajan',
                'verb' => 'arbeiten',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 3,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'pregunto',
                'verb' => 'frage',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 3,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'preguntas',
                'verb' => 'fragst',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 3,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'pregunta',
                'verb' => 'fragt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 3,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'preguntamos',
                'verb' => 'fragen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 3,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'preguntan',
                'verb' => 'fragt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 3,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'preguntan',
                'verb' => 'fragen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 4,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'creo',
                'verb' => 'glaube',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 4,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'crees',
                'verb' => 'glaubst',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 4,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'cree',
                'verb' => 'glaubt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 4,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'creemos',
                'verb' => 'glauben',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 4,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'creen',
                'verb' => 'glaubt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 4,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'creen',
                'verb' => 'glauben',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 5,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'vivir',
                'verb' => 'lebe',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 5,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'vives',
                'verb' => 'lebst',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 5,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'vive',
                'verb' => 'lebt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 5,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'vivimos',
                'verb' => 'leben',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 5,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'viven',
                'verb' => 'lebt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 5,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'viven',
                'verb' => 'leben',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 6,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'aprendo',
                'verb' => 'lerne',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 6,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'aprendes',
                'verb' => 'lernst',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 6,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'aprende',
                'verb' => 'lernt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 6,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'aprendemos',
                'verb' => 'lernen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 6,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'aprenden',
                'verb' => 'lernt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 6,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'aprenden',
                'verb' => 'lernen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 7,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'hago',
                'verb' => 'mache',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 7,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'haces',
                'verb' => 'machst',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 7,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'hace',
                'verb' => 'macht',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 7,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'hacemos',
                'verb' => 'machen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 7,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'hacen',
                'verb' => 'macht',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 7,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'hacen',
                'verb' => 'machen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 8,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'hablo',
                'verb' => 'rede',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 8,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'hablas',
                'verb' => 'redest',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 8,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'habla',
                'verb' => 'redet',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 8,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'hablamos',
                'verb' => 'reden',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 8,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'hablan',
                'verb' => 'redet',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 8,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'hablamos',
                'verb' => 'reden',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 9,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'digo',
                'verb' => 'sage',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 9,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'dices',
                'verb' => 'sagst',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 9,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'dice',
                'verb' => 'sagt',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 9,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'decimos',
                'verb' => 'sagen',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 9,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'dicen',
                'verb' => 'sagt',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 9,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'dicen',
                'verb' => 'sagen',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 10,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'juego',
                'verb' => 'spiele',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 10,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'juegas',
                'verb' => 'spielst',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 10,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'juega',
                'verb' => 'spielt',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 10,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'jugamos',
                'verb' => 'spielen',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 10,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'juegan',
                'verb' => 'spielt',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 10,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'juegan',
                'verb' => 'spielen',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            /** IRREGULARES */
            [
                'verbos_categoria' => 2,
                'verbos_id' => 33,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'ofrezco',
                'verb' => 'biete',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 33,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'ofreces',
                'verb' => 'bietest',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 33,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'ofrece',
                'verb' => 'bietet',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 33,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'ofrecemos',
                'verb' => 'bieten',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 33,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'responden',
                'verb' => 'antwortet',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 33,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'ofrecen',
                'verb' => 'bieten',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 34,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'permanezco',
                'verb' => 'bleibe',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 34,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'permaneces',
                'verb' => 'bleibst',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 34,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'permanece',
                'verb' => 'bleibt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 34,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'permanecemos',
                'verb' => 'bleiben',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 34,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'permanecen',
                'verb' => 'bleibt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 34,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'permanecen',
                'verb' => 'bleiben',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 35,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'pienso',
                'verb' => 'denke',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 35,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'piensas',
                'verb' => 'denkst',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 35,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'piensa',
                'verb' => 'denkt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 35,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'pensamos',
                'verb' => 'denken',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 35,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'piensan',
                'verb' => 'denkt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 35,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'piensan',
                'verb' => 'denken',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 36,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'aconsejo',
                'verb' => 'empfehle',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 36,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'aconsejas',
                'verb' => 'empfiehlst',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 36,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'aconseja',
                'verb' => 'empfiehlt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 36,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'aconsejamos',
                'verb' => 'empfehlen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 36,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'aconsejan',
                'verb' => 'empfehlt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 36,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'aconsejan',
                'verb' => 'empfehlen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 37,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'como',
                'verb' => 'esse',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 37,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'comes',
                'verb' => 'ißt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 37,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'come',
                'verb' => 'ißt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 37,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'comemos',
                'verb' => 'essen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 37,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'comen',
                'verb' => 'eßt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 37,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'comen',
                'verb' => 'essen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 38,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'conduzco',
                'verb' => 'fahre',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 38,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'conduces',
                'verb' => 'fährst',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 38,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'conduce',
                'verb' => 'fährt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 38,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'conducimos',
                'verb' => 'fahren',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 38,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'conducen',
                'verb' => 'fahrt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 38,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'conducen',
                'verb' => 'fahren',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 39,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'caigo',
                'verb' => 'fall',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 39,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'caes',
                'verb' => 'fällst',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 39,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'cae',
                'verb' => 'fällt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 39,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'caemos',
                'verb' => 'fallen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 39,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'caen',
                'verb' => 'fallt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 39,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'caen',
                'verb' => 'fallen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 40,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'encuentro',
                'verb' => 'finde',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 40,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'encuentras',
                'verb' => 'findest',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 40,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'encuentra',
                'verb' => 'findet',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 40,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'encontramos',
                'verb' => 'finden',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 40,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'encuentran',
                'verb' => 'findet',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 40,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'encontramos',
                'verb' => 'finden',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 41,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'doy',
                'verb' => 'gebe',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 41,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'das',
                'verb' => 'gibst',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 41,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'da',
                'verb' => 'gibt',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 41,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'damos',
                'verb' => 'geben',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 41,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'dan',
                'verb' => 'gebt',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 41,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'dan',
                'verb' => 'geben',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            /** MODALES */
            [
                'verbos_categoria' => 3,
                'verbos_id' => 65,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'puedo',
                'verb' => 'darf',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 65,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'puedes',
                'verb' => 'darfst',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 65,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'puede',
                'verb' => 'darf',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 65,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'podemos',
                'verb' => 'dürfen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 65,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'pueden',
                'verb' => 'dürft',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 65,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'pueden',
                'verb' => 'dürfen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 66,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'puedo',
                'verb' => 'kann',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 66,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'puedes',
                'verb' => 'kannst',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 66,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'puede',
                'verb' => 'kann',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 66,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'podemos',
                'verb' => 'können',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 66,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'pueden',
                'verb' => 'könnt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 66,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'pueden',
                'verb' => 'können',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 67,
                'pronombre' => 'me',
                'pronomen' => 'ich',
                'verbo' => 'mag',
                'verb' => 'gusta',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 67,
                'pronombre' => 'te',
                'pronomen' => 'du',
                'verbo' => 'gusta',
                'verb' => 'magst',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 67,
                'pronombre' => 'te',
                'pronomen' => 'er/sie/es',
                'verbo' => 'gusta',
                'verb' => 'magt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 67,
                'pronombre' => 'nos',
                'pronomen' => 'wir',
                'verbo' => 'gusta',
                'verb' => 'mögen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 67,
                'pronombre' => 'les',
                'pronomen' => 'ihr',
                'verbo' => 'gusta',
                'verb' => 'mögt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 67,
                'pronombre' => 'les',
                'pronomen' => 'sie',
                'verbo' => 'gusta',
                'verb' => 'mögen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 68,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'tengo que',
                'verb' => 'muß',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 68,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'tienes que',
                'verb' => 'mußt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 68,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'tiene que',
                'verb' => 'muß',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 68,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'tenemos que',
                'verb' => 'müßen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 68,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'tienen que',
                'verb' => 'müßt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 68,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'tienen que',
                'verb' => 'müßen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 69,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'debo',
                'verb' => 'soll',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 69,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'debes',
                'verb' => 'sollst',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 69,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'debe',
                'verb' => 'soll',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 69,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'debemos',
                'verb' => 'sollen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 69,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'deberian',
                'verb' => 'sollt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 69,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'deberian',
                'verb' => 'sollen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 70,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'quiero',
                'verb' => 'will',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 70,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'quieres',
                'verb' => 'willst',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 70,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'quiere',
                'verb' => 'will',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 70,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'queremos',
                'verb' => 'wollen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 70,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'quieren',
                'verb' => 'wollt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 70,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'quieren',
                'verb' => 'wollen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            /** AUXILIARES */
            [
                'verbos_categoria' => 4,
                'verbos_id' => 71,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'soy/estoy',
                'verb' => 'bin',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 4,
                'verbos_id' => 71,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'eres/estás',
                'verb' => 'bist',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 4,
                'verbos_id' => 71,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'es/está',
                'verb' => 'ist',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 4,
                'verbos_id' => 71,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'somos/estamos',
                'verb' => 'sind',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 4,
                'verbos_id' => 71,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'son/están',
                'verb' => 'seid',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 4,
                'verbos_id' => 71,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'son/están',
                'verb' => 'sind',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 4,
                'verbos_id' => 72,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'tengo',
                'verb' => 'habe',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 4,
                'verbos_id' => 72,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'tienes',
                'verb' => 'hast',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 4,
                'verbos_id' => 72,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'tiene',
                'verb' => 'hat',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 4,
                'verbos_id' => 72,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'tenemos',
                'verb' => 'haben',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 4,
                'verbos_id' => 72,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'tienen',
                'verb' => 'habt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 4,
                'verbos_id' => 72,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'tienen',
                'verb' => 'haben',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 4,
                'verbos_id' => 73,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'llegaré a ser',
                'verb' => 'werde',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 4,
                'verbos_id' => 73,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'llegarás a ser',
                'verb' => 'wirst',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 4,
                'verbos_id' => 73,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'es/está',
                'verb' => 'wird',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 4,
                'verbos_id' => 73,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'llegaremos a ser',
                'verb' => 'werden',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 4,
                'verbos_id' => 73,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'llegarán a ser',
                'verb' => 'werdet',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 4,
                'verbos_id' => 73,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'llegarán a ser',
                'verb' => 'werden',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
        ];

        DB::table('conjugador')->insert($verbos);
    }
}
