<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ConjugadorTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $verbos = [
            [
                'verbos_categoria' => 1,
                'verbos_id' => 1,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'respondo',
                'verb' => 'antworte',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 1,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'respondes',
                'verb' => 'antwortest',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 1,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'responde',
                'verb' => 'antwortet',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 1,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'respondemos',
                'verb' => 'antworten',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 1,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'responden',
                'verb' => 'antwortet',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 1,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'son/están',
                'verb' => 'antworten',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            /** IRREGULARES */
            [
                'verbos_categoria' => 2,
                'verbos_id' => 33,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'ofrezco',
                'verb' => 'biete',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 2,
                'verbos_id' => 33,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'ofreces',
                'verb' => 'bietest',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 33,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'ofrece',
                'verb' => 'bietet',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 33,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'ofrecemos',
                'verb' => 'bieten',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 33,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'responden',
                'verb' => 'antwortet',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 1,
                'verbos_id' => 33,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'ofrecen',
                'verb' => 'bieten',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            /** MODALES */
            [
                'verbos_categoria' => 3,
                'verbos_id' => 65,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'puedo',
                'verb' => 'darf',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 65,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'puedes',
                'verb' => 'darfst',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 65,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'puede',
                'verb' => 'darf',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 65,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'podemos',
                'verb' => 'dürfen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 65,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'pueden',
                'verb' => 'dürft',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 3,
                'verbos_id' => 65,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'pueden',
                'verb' => 'dürfen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            /** AUXILIARES */
            [
                'verbos_categoria' => 4,
                'verbos_id' => 71,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'soy/estoy',
                'verb' => 'bin',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 4,
                'verbos_id' => 71,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'eres/estás',
                'verb' => 'bist',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 4,
                'verbos_id' => 71,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'es/está',
                'verb' => 'ist',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 4,
                'verbos_id' => 71,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'somos/estamos',
                'verb' => 'sind',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 4,
                'verbos_id' => 71,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'son/están',
                'verb' => 'seid',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 4,
                'verbos_id' => 71,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'son/están',
                'verb' => 'sind',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 4,
                'verbos_id' => 72,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'tengo',
                'verb' => 'habe',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 4,
                'verbos_id' => 72,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'tienes',
                'verb' => 'hast',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 4,
                'verbos_id' => 72,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'tiene',
                'verb' => 'hat',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 4,
                'verbos_id' => 72,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'tenemos',
                'verb' => 'haben',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 4,
                'verbos_id' => 72,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'tienen',
                'verb' => 'habt',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 4,
                'verbos_id' => 72,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'tienen',
                'verb' => 'haben',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 4,
                'verbos_id' => 73,
                'pronombre' => 'yo',
                'pronomen' => 'ich',
                'verbo' => 'llegaré a ser',
                'verb' => 'werde',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 4,
                'verbos_id' => 73,
                'pronombre' => 'tú',
                'pronomen' => 'du',
                'verbo' => 'llegarás a ser',
                'verb' => 'wirst',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 4,
                'verbos_id' => 73,
                'pronombre' => 'él/ella/eso',
                'pronomen' => 'er/sie/es',
                'verbo' => 'es/está',
                'verb' => 'wird',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 4,
                'verbos_id' => 73,
                'pronombre' => 'nosotros',
                'pronomen' => 'wir',
                'verbo' => 'llegaremos a ser',
                'verb' => 'werden',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 4,
                'verbos_id' => 73,
                'pronombre' => 'ustedes',
                'pronomen' => 'ihr',
                'verbo' => 'llegarán a ser',
                'verb' => 'werdet',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'verbos_categoria' => 4,
                'verbos_id' => 73,
                'pronombre' => 'ellos',
                'pronomen' => 'sie',
                'verbo' => 'llegarán a ser',
                'verb' => 'werden',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
        ];

        DB::table('conjugador')->insert($verbos);
    }
}
