<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SustantivosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $sustantivos = [
            [
                'categoria_id' => 1,
                'articulo' => 'la',
                'sustantivo' => 'Madre',
                'artikel' => 'die',
                'substantiv' => 'Mutter',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Mütter',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 1,
                'articulo' => 'el',
                'sustantivo' => 'Padre',
                'artikel' => 'der',
                'substantiv' => 'Vater',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Vätter',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 1,
                'articulo' => 'el',
                'sustantivo' => 'Hijo',
                'artikel' => 'der',
                'substantiv' => 'Sohn',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Söhne',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 1,
                'articulo' => 'la',
                'sustantivo' => 'Hija',
                'artikel' => 'die',
                'substantiv' => 'Tochter',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Töchter',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 1,
                'articulo' => 'el',
                'sustantivo' => 'Abuelo',
                'artikel' => 'der',
                'substantiv' => 'Großvater',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Großvätter',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 1,
                'articulo' => 'la',
                'sustantivo' => 'Abuela',
                'artikel' => 'die',
                'substantiv' => 'Großmutter',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Großmütter',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 1,
                'articulo' => 'el',
                'sustantivo' => 'Hermano',
                'artikel' => 'der',
                'substantiv' => 'Bruder',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Brüder',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 1,
                'articulo' => 'la',
                'sustantivo' => 'Hermana',
                'artikel' => 'die',
                'substantiv' => 'Schwester',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Schwestern',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 1,
                'articulo' => 'el',
                'sustantivo' => 'Señor',
                'artikel' => 'der',
                'substantiv' => 'Herr',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Herren',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 1,
                'articulo' => 'la',
                'sustantivo' => 'Señora',
                'artikel' => 'die',
                'substantiv' => 'Dame',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Damen',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 1,
                'articulo' => 'el',
                'sustantivo' => 'Niño',
                'artikel' => 'der',
                'substantiv' => 'Junge',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Jungen',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 1,
                'articulo' => 'la',
                'sustantivo' => 'Niña',
                'artikel' => 'die',
                'substantiv' => 'Mädchen',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Mädchen',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 1,
                'articulo' => 'el',
                'sustantivo' => 'Anciano',
                'artikel' => 'der',
                'substantiv' => 'Ältere',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Großvätter',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 1,
                'articulo' => 'la',
                'sustantivo' => 'Anciana',
                'artikel' => 'die',
                'substantiv' => 'Alte',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Großmütter',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 1,
                'articulo' => 'el/la',
                'sustantivo' => 'Bebe',
                'artikel' => 'das',
                'substantiv' => 'Baby',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Babys',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            /** ANIMALES */
            [
                'categoria_id' => 2,
                'articulo' => 'el',
                'sustantivo' => 'Perro',
                'artikel' => 'der',
                'substantiv' => 'Hund',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Hunde',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 2,
                'articulo' => 'el/la',
                'sustantivo' => 'Gato',
                'artikel' => 'die',
                'substantiv' => 'Katze',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Katzen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 2,
                'articulo' => 'el',
                'sustantivo' => 'Pajaro',
                'artikel' => 'der',
                'substantiv' => 'Vogel',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Vögel',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 2,
                'articulo' => 'la',
                'sustantivo' => 'Gallina',
                'artikel' => 'die',
                'substantiv' => 'Henne',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Hühner',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 2,
                'articulo' => 'el',
                'sustantivo' => 'Pato',
                'artikel' => 'die',
                'substantiv' => 'Ente',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Enten',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 2,
                'articulo' => 'el',
                'sustantivo' => 'Caballo',
                'artikel' => 'das',
                'substantiv' => 'Pferd',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Pferde',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 2,
                'articulo' => 'la',
                'sustantivo' => 'Vaca',
                'artikel' => 'die',
                'substantiv' => 'Kuh',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Kühe',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 2,
                'articulo' => 'el',
                'sustantivo' => 'Puerco',
                'artikel' => 'das',
                'substantiv' => 'Schwein',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Schweine',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 2,
                'articulo' => 'el',
                'sustantivo' => 'Pez',
                'artikel' => 'der',
                'substantiv' => 'Fisch',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Fisch',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 2,
                'articulo' => 'el',
                'sustantivo' => 'Ratón',
                'artikel' => 'die',
                'substantiv' => 'Maus',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Mäuse',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 2,
                'articulo' => 'el',
                'sustantivo' => 'León',
                'artikel' => 'der',
                'substantiv' => 'Löwe',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Löwen',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 2,
                'articulo' => 'el',
                'sustantivo' => 'Tigre',
                'artikel' => 'der',
                'substantiv' => 'Tiger',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Tiger',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 2,
                'articulo' => 'la',
                'sustantivo' => 'Jirafa',
                'artikel' => 'die',
                'substantiv' => 'Giraffe',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Giraffen',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 2,
                'articulo' => 'el',
                'sustantivo' => 'Elefante',
                'artikel' => 'der',
                'substantiv' => 'Elefant',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Elefanten',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 2,
                'articulo' => 'el',
                'sustantivo' => 'Delfín',
                'artikel' => 'der',
                'substantiv' => 'Delphin',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Delfine',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 2,
                'articulo' => 'la',
                'sustantivo' => 'Ballena',
                'artikel' => 'der',
                'substantiv' => 'Wal',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Wale',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            /** LUGARES */
            [
                'categoria_id' => 3,
                'articulo' => 'la',
                'sustantivo' => 'Casa',
                'artikel' => 'das',
                'substantiv' => 'Haus',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Häuser',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 3,
                'articulo' => 'la',
                'sustantivo' => 'Escuela',
                'artikel' => 'die',
                'substantiv' => 'Schule',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Schulen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 3,
                'articulo' => 'la',
                'sustantivo' => 'Oficina',
                'artikel' => 'das',
                'substantiv' => 'Büro',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Büros',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 3,
                'articulo' => 'el',
                'sustantivo' => 'Parque',
                'artikel' => 'der',
                'substantiv' => 'Park',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Parks',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 3,
                'articulo' => 'el',
                'sustantivo' => 'Restaurante',
                'artikel' => 'das',
                'substantiv' => 'Restaurant',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Restaurants',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 3,
                'articulo' => 'la',
                'sustantivo' => 'Iglesia',
                'artikel' => 'die',
                'substantiv' => 'Kirche',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Kirchen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 3,
                'articulo' => 'el',
                'sustantivo' => 'Supermercado',
                'artikel' => 'der',
                'substantiv' => 'Supermarkt',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Supermärkte',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 3,
                'articulo' => 'el',
                'sustantivo' => 'Hotel',
                'artikel' => 'das',
                'substantiv' => 'Hotel',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Hotels',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            /** TRANSPORTE */
            [
                'categoria_id' => 4,
                'articulo' => 'el',
                'sustantivo' => 'Carro',
                'artikel' => 'das',
                'substantiv' => 'Auto',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Autos',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 4,
                'articulo' => 'el',
                'sustantivo' => 'Autobús',
                'artikel' => 'der',
                'substantiv' => 'Bus',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Busse',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 4,
                'articulo' => 'el',
                'sustantivo' => 'Barco',
                'artikel' => 'das',
                'substantiv' => 'Schiff',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Schiffe',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 4,
                'articulo' => 'la',
                'sustantivo' => 'Bicicleta',
                'artikel' => 'das',
                'substantiv' => 'Fahrrad',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Fahrräder',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 4,
                'articulo' => 'el',
                'sustantivo' => 'Avión',
                'artikel' => 'das',
                'substantiv' => 'Flugzeug',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Flugzeuge',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 4,
                'articulo' => 'la',
                'sustantivo' => 'Motocicleta',
                'artikel' => 'das',
                'substantiv' => 'Motorrad',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Motorräder',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 4,
                'articulo' => 'el',
                'sustantivo' => 'Tren',
                'artikel' => 'der',
                'substantiv' => 'Zug',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Züge',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 4,
                'articulo' => 'el',
                'sustantivo' => 'Subterráneo',
                'artikel' => 'die',
                'substantiv' => 'U-bahn',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'U-bahn',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            /** TIEMPO */
            [
                'categoria_id' => 5,
                'articulo' => 'el',
                'sustantivo' => 'Lunes',
                'artikel' => 'der',
                'substantiv' => 'Montag',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Montags',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 5,
                'articulo' => 'el',
                'sustantivo' => 'Martes',
                'artikel' => 'der',
                'substantiv' => 'Dienstag',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Dienstags',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 5,
                'articulo' => 'el',
                'sustantivo' => 'Miércoles',
                'artikel' => 'der',
                'substantiv' => 'Mittwoch',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Mittwochs',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 5,
                'articulo' => 'el',
                'sustantivo' => 'Jueves',
                'artikel' => 'der',
                'substantiv' => 'Donnerstag',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Donnerstags',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 5,
                'articulo' => 'el',
                'sustantivo' => 'Viernes',
                'artikel' => 'der',
                'substantiv' => 'Freitag',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Freitags',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 5,
                'articulo' => 'el',
                'sustantivo' => 'Sábado',
                'artikel' => 'der',
                'substantiv' => 'Samstag',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Samstags',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 5,
                'articulo' => 'el',
                'sustantivo' => 'Domingo',
                'artikel' => 'der',
                'substantiv' => 'Sonntag',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Sonntags',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 5,
                'articulo' => 'el',
                'sustantivo' => 'Enero',
                'artikel' => 'der',
                'substantiv' => 'Januar',
                'artikel_plural' => '',
                'substantiv_plural' => '',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 5,
                'articulo' => 'el',
                'sustantivo' => 'Febrero',
                'artikel' => 'der',
                'substantiv' => 'Februar',
                'artikel_plural' => '',
                'substantiv_plural' => '',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 5,
                'articulo' => 'el',
                'sustantivo' => 'Marzo',
                'artikel' => 'der',
                'substantiv' => 'März',
                'artikel_plural' => '',
                'substantiv_plural' => '',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 5,
                'articulo' => 'el',
                'sustantivo' => 'Abril',
                'artikel' => 'der',
                'substantiv' => 'April',
                'artikel_plural' => '',
                'substantiv_plural' => '',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 5,
                'articulo' => 'el',
                'sustantivo' => 'Mayo',
                'artikel' => 'der',
                'substantiv' => 'Mai',
                'artikel_plural' => '',
                'substantiv_plural' => '',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 5,
                'articulo' => 'el',
                'sustantivo' => 'Junio',
                'artikel' => 'der',
                'substantiv' => 'Juni',
                'artikel_plural' => '',
                'substantiv_plural' => '',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 5,
                'articulo' => 'el',
                'sustantivo' => 'Julio',
                'artikel' => 'der',
                'substantiv' => 'Juli',
                'artikel_plural' => '',
                'substantiv_plural' => '',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 5,
                'articulo' => 'el',
                'sustantivo' => 'Agosto',
                'artikel' => 'der',
                'substantiv' => 'August',
                'artikel_plural' => '',
                'substantiv_plural' => '',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 5,
                'articulo' => 'el',
                'sustantivo' => 'Septiembre',
                'artikel' => 'der',
                'substantiv' => 'September',
                'artikel_plural' => '',
                'substantiv_plural' => '',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 5,
                'articulo' => 'el',
                'sustantivo' => 'Octubre',
                'artikel' => 'der',
                'substantiv' => 'Oktober',
                'artikel_plural' => '',
                'substantiv_plural' => '',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 5,
                'articulo' => 'el',
                'sustantivo' => 'Noviembre',
                'artikel' => 'der',
                'substantiv' => 'November',
                'artikel_plural' => '',
                'substantiv_plural' => '',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 5,
                'articulo' => 'el',
                'sustantivo' => 'Diciembre',
                'artikel' => 'der',
                'substantiv' => 'Dezember',
                'artikel_plural' => '',
                'substantiv_plural' => '',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 5,
                'articulo' => 'la',
                'sustantivo' => 'Primavera',
                'artikel' => 'der',
                'substantiv' => 'Frühling',
                'artikel_plural' => '',
                'substantiv_plural' => '',
                'nivel' => 3,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 5,
                'articulo' => 'el',
                'sustantivo' => 'Verano',
                'artikel' => 'der',
                'substantiv' => 'Sommer',
                'artikel_plural' => '',
                'substantiv_plural' => '',
                'nivel' => 3,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 5,
                'articulo' => 'el',
                'sustantivo' => 'Otoño',
                'artikel' => 'der',
                'substantiv' => 'Herbst',
                'artikel_plural' => '',
                'substantiv_plural' => '',
                'nivel' => 3,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 5,
                'articulo' => 'el',
                'sustantivo' => 'Invierno',
                'artikel' => 'der',
                'substantiv' => 'Winter',
                'artikel_plural' => '',
                'substantiv_plural' => '',
                'nivel' => 3,
                'created_at' => Carbon::now(),
            ],
        ];

        DB::table('sustantivos')->insert($sustantivos);
    }
}
