<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SustantivosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $sustantivos = [
            [
                'categoria_id' => 1,
                'articulo' => 'la',
                'sustantivo' => 'Madre',
                'artikel' => 'die',
                'substantiv' => 'Mutter',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Mütter',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 1,
                'articulo' => 'el',
                'sustantivo' => 'Padre',
                'artikel' => 'der',
                'substantiv' => 'Vater',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Vätter',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 1,
                'articulo' => 'el',
                'sustantivo' => 'Hijo',
                'artikel' => 'der',
                'substantiv' => 'Sohn',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Söhne',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 1,
                'articulo' => 'la',
                'sustantivo' => 'Hija',
                'artikel' => 'die',
                'substantiv' => 'Tochter',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Töchter',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 1,
                'articulo' => 'el',
                'sustantivo' => 'Abuelo',
                'artikel' => 'der',
                'substantiv' => 'Großvater',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Großvätter',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 1,
                'articulo' => 'la',
                'sustantivo' => 'Abuela',
                'artikel' => 'die',
                'substantiv' => 'Großmutter',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Großmütter',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 1,
                'articulo' => 'el',
                'sustantivo' => 'Hermano',
                'artikel' => 'der',
                'substantiv' => 'Bruder',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Brüder',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 1,
                'articulo' => 'la',
                'sustantivo' => 'Hermana',
                'artikel' => 'die',
                'substantiv' => 'Schwester',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Schwestern',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 1,
                'articulo' => 'el',
                'sustantivo' => 'Señor',
                'artikel' => 'der',
                'substantiv' => 'Herr',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Herren',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 1,
                'articulo' => 'la',
                'sustantivo' => 'Señora',
                'artikel' => 'die',
                'substantiv' => 'Dame',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Damen',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 1,
                'articulo' => 'el',
                'sustantivo' => 'Niño',
                'artikel' => 'der',
                'substantiv' => 'Junge',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Jungen',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 1,
                'articulo' => 'la',
                'sustantivo' => 'Niña',
                'artikel' => 'die',
                'substantiv' => 'Mädchen',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Mädchen',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 1,
                'articulo' => 'el',
                'sustantivo' => 'Anciano',
                'artikel' => 'der',
                'substantiv' => 'Ältere',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Großvätter',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 1,
                'articulo' => 'la',
                'sustantivo' => 'Anciana',
                'artikel' => 'die',
                'substantiv' => 'Alte',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Großmütter',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 1,
                'articulo' => 'el/la',
                'sustantivo' => 'Bebe',
                'artikel' => 'das',
                'substantiv' => 'Baby',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Babys',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 2,
                'articulo' => 'el',
                'sustantivo' => 'Perro',
                'artikel' => 'der',
                'substantiv' => 'Hund',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Hunde',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 2,
                'articulo' => 'el/la',
                'sustantivo' => 'Gato',
                'artikel' => 'die',
                'substantiv' => 'Katze',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Katzen',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 2,
                'articulo' => 'el',
                'sustantivo' => 'Pajaro',
                'artikel' => 'der',
                'substantiv' => 'Vogel',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Vögel',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 2,
                'articulo' => 'la',
                'sustantivo' => 'Gallina',
                'artikel' => 'die',
                'substantiv' => 'Henne',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Hühner',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 2,
                'articulo' => 'el',
                'sustantivo' => 'Pato',
                'artikel' => 'die',
                'substantiv' => 'Ente',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Enten',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 2,
                'articulo' => 'el',
                'sustantivo' => 'Caballo',
                'artikel' => 'das',
                'substantiv' => 'Pferd',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Pferde',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 2,
                'articulo' => 'la',
                'sustantivo' => 'Vaca',
                'artikel' => 'die',
                'substantiv' => 'Kuh',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Kühe',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
            [
                'categoria_id' => 2,
                'articulo' => 'el',
                'sustantivo' => 'Puerco',
                'artikel' => 'das',
                'substantiv' => 'Schwein',
                'artikel_plural' => 'die',
                'substantiv_plural' => 'Schweine',
                'nivel' => 1,
                'created_at' => Carbon::now(),
            ],
        ];

        DB::table('sustantivos')->insert($sustantivos);
    }
}
