<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VerbosIrregularesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $verbos = [
            /** IRREGULARES */

            [
                'verbo_categoria_id' => 2,
                'nivel' => 1,
                'verbo' => 'Ofrecer',
                'verb' => 'Bieten',
                'ejemplo' => 'Me ofrecen un viaje gratis',
                'exampel' => 'Sie bieten mir eine kostenlose Reise an',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 2,
                'nivel' => 1,
                'verbo' => 'Permanecer',
                'verb' => 'Bleiben',
                'ejemplo' => 'Todos permanecemos unidos',
                'exampel' => 'Wir bleiben gemeinsam',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 2,
                'nivel' => 1,
                'verbo' => 'Pensar',
                'verb' => 'Denken',
                'ejemplo' => 'El sacerdote piensa en Dios',
                'exampel' => 'Der Priester denkt an Gott',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 2,
                'nivel' => 1,
                'verbo' => 'Aconsejar',
                'verb' => 'Empfehlen',
                'ejemplo' => 'La doctora nos recomienda tomar medicamentos',
                'exampel' => 'Die Ärztin empfiehlt uns trinken Medikamenten',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 2,
                'nivel' => 1,
                'verbo' => 'Comer',
                'verb' => 'Essen',
                'ejemplo' => 'Los leones comen humanos',
                'exampel' => 'Löwen essen Menschen',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 2,
                'nivel' => 1,
                'verbo' => 'Conducir',
                'verb' => 'Fahren',
                'ejemplo' => 'El conduce por la ciudad',
                'exampel' => 'Er fährt durch die Stadt',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 2,
                'nivel' => 1,
                'verbo' => 'Caer',
                'verb' => 'Fallen',
                'ejemplo' => 'Los angeles malos caen del cielo',
                'exampel' => 'Die Bösen Engeln fallen vom Himmel',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 2,
                'nivel' => 1,
                'verbo' => 'Encontrar',
                'verb' => 'Finden',
                'ejemplo' => 'Encontrar un cine es tu prioridad',
                'exampel' => 'Ein Kino zu finden ist dein Priorität',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 2,
                'nivel' => 2,
                'verbo' => 'Dar',
                'verb' => 'Geben',
                'ejemplo' => 'Me ofrecen un viaje gratis',
                'exampel' => 'Sie bieten mir eine kostenlose Reise an',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 2,
                'nivel' => 2,
                'verbo' => 'Ir',
                'verb' => 'Gehen',
                'ejemplo' => 'Voy al supermercado',
                'exampel' => 'Ich gehe zum Supermarkt',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 2,
                'nivel' => 2,
                'verbo' => 'Ayudar',
                'verb' => 'Helfen',
                'ejemplo' => 'La cruz roja ayuda',
                'exampel' => 'Das rote Kreus hilft',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 2,
                'nivel' => 2,
                'verbo' => 'Conocer',
                'verb' => 'Kennen',
                'ejemplo' => 'El chofer conoce el camino',
                'exampel' => 'Der Fahrer kennt den Weg',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 2,
                'nivel' => 2,
                'verbo' => 'Venir',
                'verb' => 'Kommen',
                'ejemplo' => 'Ella viene de Australia',
                'exampel' => 'Sie kommt aus Australien',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 2,
                'nivel' => 2,
                'verbo' => 'Cargar',
                'verb' => 'Laden',
                'ejemplo' => 'El caballo carga 100 kilogramos',
                'exampel' => 'Das Pferd lädt 100 Kilogramm',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 2,
                'nivel' => 2,
                'verbo' => 'Dejar',
                'verb' => 'Lassen',
                'ejemplo' => 'Dejamos nuestros sueños',
                'exampel' => 'Wir lassen unsere Träume',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 2,
                'nivel' => 2,
                'verbo' => 'Leer',
                'verb' => 'Lesen',
                'ejemplo' => 'Los filósofos leen mucho',
                'exampel' => 'Philosophen lesen viel',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 2,
                'nivel' => 3,
                'verbo' => 'Yacer',
                'verb' => 'Liegen',
                'ejemplo' => 'El gato esta sobr el sofá',
                'exampel' => 'Die Katze liegt auf Sofa',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 2,
                'nivel' => 3,
                'verbo' => 'Tomar',
                'verb' => 'Nehmen',
                'ejemplo' => 'Toma las llaves',
                'exampel' => 'Du nimmst die Schlüssen',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 2,
                'nivel' => 3,
                'verbo' => 'Cerrar',
                'verb' => 'Schließen',
                'ejemplo' => 'Las puertas estan cerradas',
                'exampel' => 'Die Tür sind geschlossen',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 2,
                'nivel' => 3,
                'verbo' => 'Escribir',
                'verb' => 'Schreiben',
                'ejemplo' => 'Escribir libros es difícil',
                'exampel' => 'Büchen zu schreiben ist schwierig',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 2,
                'nivel' => 3,
                'verbo' => 'Ver',
                'verb' => 'Sehen',
                'ejemplo' => 'Los videntes ven el futuro',
                'exampel' => 'Seher sehen die Zukunft',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 2,
                'nivel' => 3,
                'verbo' => 'Enviar',
                'verb' => 'Senden',
                'ejemplo' => 'Te estamos enviando una pelicula',
                'exampel' => 'Wir senden dir einen Film',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 2,
                'nivel' => 3,
                'verbo' => 'Hablar',
                'verb' => 'Sprechen',
                'ejemplo' => 'Sprechen die Tiere?',
                'exampel' => '¿Hablan los animales?',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 2,
                'nivel' => 3,
                'verbo' => 'Estar de pie',
                'verb' => 'Stehen',
                'ejemplo' => 'Soldados, de pie!',
                'exampel' => 'Soldaten, steh auf!',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 2,
                'nivel' => 4,
                'verbo' => 'Llevar',
                'verb' => 'Tragen',
                'ejemplo' => 'La carta lleva paz al mundo',
                'exampel' => 'Das Brief trägt Frieden in die Welt',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 2,
                'nivel' => 4,
                'verbo' => 'Encontrar',
                'verb' => 'Treffen',
                'ejemplo' => 'El pirata se encuentra al Kraken',
                'exampel' => 'Der Pirat trifft den Kraken',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 2,
                'nivel' => 4,
                'verbo' => 'Olvidar',
                'verb' => 'Vergessen',
                'ejemplo' => 'Siempre olvidas lo que es importante',
                'exampel' => 'Du vergisst immer, was wichtig ist',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 2,
                'nivel' => 4,
                'verbo' => 'Saber',
                'verb' => 'Wißen',
                'ejemplo' => 'Sabemos poco sobre el universo',
                'exampel' => 'Wir wißen wenig über das Universum',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 2,
                'nivel' => 4,
                'verbo' => 'Empezar',
                'verb' => 'Beginnen',
                'ejemplo' => 'El viajero comienza su viaje',
                'exampel' => 'Der Reisende beginnt seine Reise',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 2,
                'nivel' => 4,
                'verbo' => 'Inducir',
                'verb' => 'Bewegen',
                'ejemplo' => 'El induce personas al mal',
                'exampel' => 'Er bewegt Menschen zum Übel',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 2,
                'nivel' => 4,
                'verbo' => 'Pedir',
                'verb' => 'Bitten',
                'ejemplo' => 'Pedimos la cuenta',
                'exampel' => 'Wir bitten um das Konto',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 2,
                'nivel' => 4,
                'verbo' => 'Traer',
                'verb' => 'Bringen',
                'ejemplo' => 'La muerte trae tristeza',
                'exampel' => 'Der Tod bringt Traurigkeit',
                'created_at' => Carbon::now(),
            ],
        ];

        DB::table('verbos')->insert($verbos);
    }
}
