<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VerbosRegularesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $verbos = [
            /** REGULARES */

            [
                'verbo_categoria_id' => 1,
                'nivel' => 1,
                'verbo' => 'Responder',
                'verb' => 'Antworten',
                'ejemplo' => 'Respondo a la profesora',
                'exampel' => 'Ich antworte dem Lehrerin',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 1,
                'nivel' => 1,
                'verbo' => 'Trabajar',
                'verb' => 'Arbeiten',
                'ejemplo' => 'El trabajo es necesario',
                'exampel' => 'Die Arbeit ist not',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 1,
                'nivel' => 1,
                'verbo' => 'Preguntar',
                'verb' => 'Fragen',
                'ejemplo' => 'El pregunta la hora',
                'exampel' => 'Er fragt die Zeit',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 1,
                'nivel' => 1,
                'verbo' => 'Creer',
                'verb' => 'Glauben',
                'ejemplo' => 'Yo creo en mi mismo',
                'exampel' => 'Ich glaube an mich',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 1,
                'nivel' => 1,
                'verbo' => 'Vivir',
                'verb' => 'Leben',
                'ejemplo' => 'El perro esta con vida',
                'exampel' => 'Der Hund lebt',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 1,
                'nivel' => 1,
                'verbo' => 'Aprender',
                'verb' => 'Lernen',
                'ejemplo' => 'Todos aprendemos',
                'exampel' => 'Wir alle lernen',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 1,
                'nivel' => 1,
                'verbo' => 'Hacer',
                'verb' => 'Machen',
                'ejemplo' => 'Ellos hacen comida',
                'exampel' => 'Sie machen Essen ',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 1,
                'nivel' => 1,
                'verbo' => 'Hablar',
                'verb' => 'Reden',
                'ejemplo' => 'Yo hablo con el profesor',
                'exampel' => 'Ich rede mit den Lehrer',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 1,
                'nivel' => 2,
                'verbo' => 'Decir',
                'verb' => 'Sagen',
                'ejemplo' => 'Todos decimos lo que pensamos',
                'exampel' => 'Wir alle sagen was wir denken',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 1,
                'nivel' => 2,
                'verbo' => 'Jugar',
                'verb' => 'Spielen',
                'ejemplo' => 'La niña juega con muñecas',
                'exampel' => 'Das mädchen spielt mit Puppen',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 1,
                'nivel' => 2,
                'verbo' => 'Construir',
                'verb' => 'Bauen',
                'ejemplo' => 'Yo construyo casas',
                'exampel' => 'Ich baue Hausen',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 1,
                'nivel' => 2,
                'verbo' => 'Significar',
                'verb' => 'Bedeuten',
                'ejemplo' => 'El cartel significa muerte',
                'exampel' => 'Das plakat bedeutet Tod',
                'nivel' => 2,
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 1,
                'nivel' => 2,
                'verbo' => 'Formar',
                'verb' => 'Bilden',
                'ejemplo' => 'Ella forma un muñeco de nieve',
                'exampel' => 'Sie bildet einen Schneemann',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 1,
                'nivel' => 2,
                'verbo' => 'Desarrollar',
                'verb' => 'Entwickeln',
                'ejemplo' => 'Yo desarrollo una página',
                'exampel' => 'Ich entwickeln eine Seite',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 1,
                'nivel' => 2,
                'verbo' => 'Acordarse',
                'verb' => 'Erinnern',
                'ejemplo' => 'No recordamos la dirección',
                'exampel' => 'Wir erinnern uns nicht die Adresse',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 1,
                'nivel' => 2,
                'verbo' => 'Aclarar',
                'verb' => 'Erklären',
                'ejemplo' => 'Tu aclaras el error',
                'exampel' => 'Du erklärt dieses Fehler',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 1,
                'nivel' => 3,
                'verbo' => 'Alcanzar',
                'verb' => 'Erreichen',
                'ejemplo' => 'El gato alcanza al ratón',
                'exampel' => 'Die Katze erreicht die Maus',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 1,
                'nivel' => 3,
                'verbo' => 'Narrar',
                'verb' => 'Erzählen',
                'ejemplo' => 'El periodista narra el suceso',
                'exampel' => 'Der Journalist erzählt das Ereignis',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 1,
                'nivel' => 3,
                'verbo' => 'Faltar',
                'verb' => 'Fehlen',
                'ejemplo' => 'Nos falta dinero',
                'exampel' => 'Wir fehlen Geld',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 1,
                'nivel' => 3,
                'verbo' => 'Seguir',
                'verb' => 'Folgen',
                'ejemplo' => 'Siguen a su líder',
                'exampel' => 'Sie folgen ihrem Anführer',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 1,
                'nivel' => 3,
                'verbo' => 'Sentir',
                'verb' => 'Fühlen',
                'ejemplo' => 'Siento su inconformidad',
                'exampel' => 'Ich fühle ihr Unmut',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 1,
                'nivel' => 3,
                'verbo' => 'Guiar',
                'verb' => 'Führen',
                'ejemplo' => 'La luz nos guía',
                'exampel' => 'Das licht führt uns',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 1,
                'nivel' => 3,
                'verbo' => 'Pertenecer',
                'verb' => 'Gehören',
                'ejemplo' => 'El carro pertenece a Mario',
                'exampel' => 'Das Auto gehört Mario',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 1,
                'nivel' => 3,
                'verbo' => 'Comerciar',
                'verb' => 'Handeln',
                'ejemplo' => 'Actuamos en el teatro',
                'exampel' => 'Wir handeln in die Theater',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 1,
                'nivel' => 4,
                'verbo' => 'Interesar',
                'verb' => 'Interessieren',
                'ejemplo' => 'El retrato interesa a todos',
                'exampel' => 'Das Porträt interessiert alle',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 1,
                'nivel' => 4,
                'verbo' => 'Comprar',
                'verb' => 'Kaufen',
                'ejemplo' => 'Es época de compras navideñas',
                'exampel' => 'Es ist Weihnachten Kaufen Epoche',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 1,
                'nivel' => 4,
                'verbo' => 'Cuidar',
                'verb' => 'Kümmern',
                'ejemplo' => 'La enfermera cuida a sus pacientes',
                'exampel' => 'Die Krankenschwester kümmert ihre Patienten',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 1,
                'nivel' => 4,
                'verbo' => 'Poner',
                'verb' => 'Legen',
                'ejemplo' => 'Ponemos el dinero faltante',
                'exampel' => 'Wir legen das fehlende Geld an',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 1,
                'nivel' => 4,
                'verbo' => 'Pensar',
                'verb' => 'Meinen',
                'ejemplo' => 'Tu piensas todo el día',
                'exampel' => 'Du meinst den ganzen Tag',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 1,
                'nivel' => 4,
                'verbo' => 'Llover',
                'verb' => 'Regnen',
                'ejemplo' => 'En invierno siempre llueve',
                'exampel' => 'Im Winter regnet es immer',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 1,
                'nivel' => 4,
                'verbo' => 'Gustar (comida)',
                'verb' => 'Schmecken',
                'ejemplo' => 'Me gusta esta langosta',
                'exampel' => 'Ich schmecke dieses Languste',
                'created_at' => Carbon::now(),
            ],
            [
                'verbo_categoria_id' => 1,
                'nivel' => 4,
                'verbo' => 'Estudiar',
                'verb' => 'Studieren',
                'ejemplo' => 'Los alumnos no estudian',
                'exampel' => 'Die Studenten studieren nicht',
                'created_at' => Carbon::now(),
            ],
        ];

        DB::table('verbos')->insert($verbos);
    }
}
